name: Angular CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm run test --run

      - name: Construir aplicación
        run: npm run build
        